// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKrOaJP8cyApDju7pEnhsmpHDL1mlEsgg',
    appId: '1:583284933861:web:16825cac3ec25058a4800c',
    messagingSenderId: '583284933861',
    projectId: 'capitalexpressapp-c03c5',
    authDomain: 'capitalexpressapp-c03c5.firebaseapp.com',
    storageBucket: 'capitalexpressapp-c03c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHiAQS3-4tQg6doCQB-xJtGeukbFQwtE',
    appId: '1:583284933861:android:5c200fc697a2a48ea4800c',
    messagingSenderId: '583284933861',
    projectId: 'capitalexpressapp-c03c5',
    storageBucket: 'capitalexpressapp-c03c5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKrOaJP8cyApDju7pEnhsmpHDL1mlEsgg',
    appId: '1:583284933861:web:73f434a19ebbfe50a4800c',
    messagingSenderId: '583284933861',
    projectId: 'capitalexpressapp-c03c5',
    authDomain: 'capitalexpressapp-c03c5.firebaseapp.com',
    storageBucket: 'capitalexpressapp-c03c5.firebasestorage.app',
  );
}
